### PR TITLE
This revised readme file improves the formatting

### PR DESCRIPTION
**Pull request by Saunakghosh10**
This revised readme file improves the formatting, enhances readability, and provides a more engaging and informative description of the Discord Bot Template.

### CODE REVIEW

**Comment by RileCraft** [comment]
I appreciate the effort but all changes must be first made to the `Unstable` branch instead of direct pull request to the main branch.

**Comment by Saunakghosh10** [comment]
ok sure..

**Comment by Saunakghosh10** [comment]
hey, i can see the unstable branch but cannot find it in vs code..idk y..so if I create a new branch will there be any problem?

**Comment by RileCraft** [comment]
Try the command `git checkout Unstable` in vsc.

**Comment by Saunakghosh10** [comment]
okay

**Pull request closed without merging**
