### PR TITLE
feat: @6.0.4 New Changes.

### PR DESCRIPTION
**Pull request by Zaid-maker**
i have updated package.json read the commits to know what i have done. Thank you

### CODE REVIEW

**Comment by Zaid-maker** [comment]
@RileCraft

**Comment by RileCraft** [comment]
First thanks for putting your time into this template, i want to keep required packages as low as possible and also i feel like it should be a choice on the user's side whether they want it or not as i personally also don't use nodemon and have seen many not do so as well. If they want nodemon or something like pm2 then they can just add it themself and use it according to their need.

**Comment by RileCraft** [comment]
The other changes are very minor and can be delayed so eh

**Comment by Zaid-maker** [comment]
No minor changes those are important because that's dumb to install
dependencies which already comes with nodejs

**Pull request closed without merging**
