### PR TITLE
MySQL Implementation

### PR DESCRIPTION
**Pull request by GoldO-dev**
This pull request adds MySQL compatability to the bot. This is done using a npm package called [mysql](https://www.npmjs.com/package/mysql#table-of-contents)

Link to the commit with the code: [https://github.com/RileCraft/DiscordBot-Template/pull/88/commits/ac9e705c0271c7bbf6e5294760e9b94fcce43646](https://github.com/RileCraft/DiscordBot-Template/pull/88/commits/ac9e705c0271c7bbf6e5294760e9b94fcce43646)

### CODE REVIEW

**Comment by RileCraft** [comment]
I do not see the point of implementing an external database in the template. If the user wishes to implement a database then they are free to manually do so as they please.

**Comment by GoldO-dev** [comment]
Okay, the reason I've made a implementation like this, is because I personally have been asked over 20 times to implement a mysql database into this template. 

I also personally think that it being implemented by default would make it easier for the user to make what they want using this template more easily.

Would you consider maybe adding it as a separate branch? So people can choose if they want to use it with a MySQL implementation.

**Comment by RileCraft** [comment]
I am not knowledgeable about MySQL and i already struggle with maintaining as this is currently and also if i make branch for MySQL then more people will ask for other databases or features which will create it's own mess.

**Comment by GoldO-dev** [comment]
Okay it makes sense.

**Pull request closed without merging**
